CREATE TABLE users (
                       id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX uk_users_username_lower
    ON users (lower(username));